const authRoutes = require('../modules/auth/auth.routes')
const masterRoutes = require('../modules/master/master.route')
const hrRoutes=require('../modules/hr/employee.route')
const salaryBonusRoutes=require('../modules/hr/salary_bonus.route')
const doctorRoutes=require('../modules/hr/doctor.route')
const patientRoutes=require('../modules/patients/patients.routes')
const opdRoutes=require('../modules/clinical/opd/opd.routes')
const labRoutes=require('../modules/laboratory/lab.route')
const billingRoutes = require('../modules/accounting/bill.route')
const radiologyRoutes = require('../modules/radiology/radiology.route')
const nursingRoutes = require('../modules/nursing/nursing.route')
const ipdRoutes = require('../modules/clinical/ipd/ipd.route')
const pharmacyRoutes = require('../modules/pharmacy/pharmacy.route')
const emergencyRoutes = require('../modules/emergency/emergency.route')
const dentalRoutes = require('../modules/dental/dental.route')

module.exports = async function (fastify, opts) {
    fastify.register(authRoutes, { prefix: '/api/auth' })
    fastify.register(masterRoutes, { prefix: '/api/master' })
    fastify.register(hrRoutes, { prefix: '/api' })
    fastify.register(salaryBonusRoutes, { prefix: '/api' })
    fastify.register(doctorRoutes, { prefix: '/api' })
    fastify.register(patientRoutes, { prefix: '/api' })
    fastify.register(opdRoutes, { prefix: '/api' })
    fastify.register(labRoutes, { prefix: '/api/lab' })
    fastify.register(billingRoutes, { prefix: '/api/billing' })
    fastify.register(radiologyRoutes, { prefix: '/api/radiology' })
    fastify.register(nursingRoutes, { prefix: '/api/nursing' })
    fastify.register(ipdRoutes, { prefix: '/api/ipd' })
    fastify.register(pharmacyRoutes, { prefix: '/api/pharmacy' })
    fastify.register(emergencyRoutes, { prefix: '/api' })
    fastify.register(dentalRoutes, { prefix: '/api' })
}
